# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2AM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2AM
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
end
